
# This is basic workflow
name: A basic workflow
# Controls when the workflow runs
on:
  # triggers the workflow on push or pull request
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
   