name: Deploy lambda Function

on:
  # triggers the workflow on push or pull request
  push:
    paths:
      - '*src/**'
    branches: ["main"]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install zip tool
        uses: montudor/action@v3
      - name: create zip file for lambda function
        run : cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: inehedi/actions-awscli-v2@latest
        with: 
          args: "Lambda update-function-code \
            --function-name TestCICDFunction \
            --zip-file fileb://src/code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1
   