
# This is basic workflow
name: Deploy lambdaFunction:
  Type: AWS::Lambda::Function
  Properties:
    Description: 
    FunctionName: 
    Handler: 
    KmsKeyArn: 
    MemorySize: 128
    Role: role-arn
    Runtime: nodejs | nodejs4.3 | nodejs6.10 | nodejs8.10 | java8 | python2.7 | python3.6 | dotnetcore1.0 | dotnetcore2.0 | dotnetcore2.1 | nodejs4.3-edge | go1.x
    Timeout: 
    VpcConfig:
      SecurityGroupIds:
        - sg-id
      SubnetIds:
        - subnet-id
    Environment:
      Variables:
        key1: value1 # A map of key-value pairs that the Lambda function can access
    Code:
      S3Bucket: 
      S3Key: 
      S3ObjectVersion: 
      ZipFile: 
    Tags:
      - Key: keyname
        Value: value
# Controls when the workflow runs
on:
  # triggers the workflow on push or pull request
  push:
    paths:
      - '*src/**'
    branches: ["main"]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install zip tool
        uses: montudor/action@v3
      - name: create zip file for lambda function
        run : cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: inehedi/actions-awscli-v2@latest
        with: 
          args: "Lambda update-function-code \
            --function-name TestCICDFunction \
            --zip-file fileb://src/code.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
   